%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.20.0

-ifndef(protocol_pb).
-define(protocol_pb, true).

-define(protocol_pb_gpb_version, "4.20.0").


-ifndef('PROTOCOL_REQUEST_PB_H').
-define('PROTOCOL_REQUEST_PB_H', true).
-record(protocol_request,
        {cmd                    :: unknown | keep_alive | user_login | integer() | undefined, % = 1, required, enum protocol_cmd
         body                   :: iodata() | undefined % = 2, required
        }).
-endif.

-ifndef('PROTOCOL_RESPONSE_PB_H').
-define('PROTOCOL_RESPONSE_PB_H', true).
-record(protocol_response,
        {cmd                    :: unknown | keep_alive | user_login | integer() | undefined, % = 1, required, enum protocol_cmd
         code                   :: non_neg_integer() | undefined, % = 2, required, 32 bits
         body                   :: iodata() | undefined % = 3, required
        }).
-endif.

-ifndef('KEEP_ALIVE_REQUEST_PB_H').
-define('KEEP_ALIVE_REQUEST_PB_H', true).
-record(keep_alive_request,
        {
        }).
-endif.

-ifndef('KEEP_ALIVE_RESPONSE_PB_H').
-define('KEEP_ALIVE_RESPONSE_PB_H', true).
-record(keep_alive_response,
        {
        }).
-endif.

-ifndef('USER_LOGIN_REQUEST_PB_H').
-define('USER_LOGIN_REQUEST_PB_H', true).
-record(user_login_request,
        {username               :: unicode:chardata() | undefined, % = 1, required
         password               :: unicode:chardata() | undefined % = 2, required
        }).
-endif.

-ifndef('USER_LOGIN_RESPONSE_PB_H').
-define('USER_LOGIN_RESPONSE_PB_H', true).
-record(user_login_response,
        {user_id                :: non_neg_integer() | undefined % = 1, required, 64 bits
        }).
-endif.

-endif.
